site:
  name: "Perú"
  locale: en
  meta_keywords: "peru, marca pais"
  meta_description: "Dicen que hay un Perú para cada quien"

  pages:
    index:
      published: true
    events:
      title: Agenda
      published: true
      listed: false
    news:
      published: true
      listed: false
    about:
      title: Acerca de
      published: true
      listed: false
    marca-peru:
      title: La marca Perú
      published: true
    que_es_marca_pais:
      title: Qué es una Marca País
      published: true
    desarrollo:
      title: Cómo se desarrolló
      published: true
    importancia:
      title: Por qué una Marca País
      published: true
    contact:
      title: Contáctanos
      published: true
      listed: false
    "news/template":
      title: Plantilla de una noticia
      content_type: articles
    "events/template":
      title: Plantilla de un evento
      content_type: events
    404:
      title: Page not found
      published: true

  content_types:
    "Noticias":
      description: "Lista de noticias del sitio"
      slug: articles
      order_by: date
      highlighted_field_name: title
      api_enabled: false
      fields:
        - title:
            label: Título
            hint: Título de la noticia
        - summary:
            kind: text
            label: Resumen
            hint: Texto corto mostrado en la página principal
        - body:
            kind: text
            label: Contenido
            hint: Contenido de la noticia
        - photo:
            kind: file
            label: Foto
            hint: Imagen o foto de la noticia
        - date:
            kind: date
            label: Fecha
            hint: Fecha de publicación
      contents:
        - "Presentación de Marca Perú":
            summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod nisl nec lorem bibendum quis malesuada velit luctus."
            body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod nisl nec lorem bibendum quis malesuada velit luctus. In dictum, leo ut lacinia fringilla, velit mauris ornare nisl, vitae fermentum lectus tellus ut turpis. Cras in nulla odio. Donec mollis neque eget dui dictum euismod vitae et tortor. Vivamus sagittis sapien ut enim varius tempor ultrices diam semper. Vivamus viverra erat vel eros viverra gravida. Aenean eu magna vel velit consequat euismod non id libero. Cras hendrerit tempus turpis, at placerat dui varius at. Fusce in pellentesque mauris. Nunc volutpat venenatis metus, eu blandit nibh pharetra vel."
            date: 04/01/2010
        - "Lorem ipsum dolor sit amet":
            summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod nisl nec lorem bibendum quis malesuada velit luctus."
            body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod nisl nec lorem bibendum quis malesuada velit luctus. In dictum, leo ut lacinia fringilla, velit mauris ornare nisl, vitae fermentum lectus tellus ut turpis. Cras in nulla odio. Donec mollis neque eget dui dictum euismod vitae et tortor. Vivamus sagittis sapien ut enim varius tempor ultrices diam semper. Vivamus viverra erat vel eros viverra gravida. Aenean eu magna vel velit consequat euismod non id libero. Cras hendrerit tempus turpis, at placerat dui varius at. Fusce in pellentesque mauris. Nunc volutpat venenatis metus, eu blandit nibh pharetra vel."
            date: 03/01/2010

    "Eventos":
      description: "Lista de eventos"
      slug: events
      order_by: date
      highlighted_field_name: title
      fields:
        - title:
            label: Título
            hint: Título del evento
        - summary:
            kind: text
            label: Resumen
            hint: Texto corto mostrado en la página principal
        - body:
            kind: text
            label: Descripción
            hint: Descripción del evento
        - photo:
            kind: file
            label: Foto
            hint: Imagen o foto del evento
        - city:
            label: Ciudad
            hint: Ciudad del evento
        - country:
            label: País
            hint: País del evento
        - start_date:
            kind: date
            label: Fecha de inicio
        - end_date:
            kind: date
            label: Fecha de término
      contents:
        - "Lorem ipsum dolor sit amet":
            summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod nisl nec lorem bibendum quis malesuada velit luctus."
            body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod nisl nec lorem bibendum quis malesuada velit luctus. In dictum, leo ut lacinia fringilla, velit mauris ornare nisl, vitae fermentum lectus tellus ut turpis."
            start_date: 08/03/2011
            end_date: 10/03/2011
        - "Ceremonio de Presentación de Marca Perú":
            summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod nisl nec lorem bibendum quis malesuada velit luctus."
            body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod nisl nec lorem bibendum quis malesuada velit luctus. In dictum, leo ut lacinia fringilla, velit mauris ornare nisl, vitae fermentum lectus tellus ut turpis."
            start_date: 08/03/2011
            end_date: 10/03/2011

    "Recursos":
      description: "List de recursos usandos en los eventos"
      slug: resources
      order_by: manually
      fields:
        - name:
            label: Nombre
        - description:
            kind: text
            label: Descripción
        - source:
            kind: file
            label: Archivo
            hint: Archivo descargable de este recurso
        - event:
            kind: string
            label: Evento
            hint: Evento asociado a este recurso

    "Mensajes":
      description: "Mensajes enviados por los visitantes"
      slug: messages
      highlighted_field_name: name
      api_enabled: true
      order_by: date
      fields:
        - name:
            label: Nombre
        - email:
            label: Correo electrónico
        - message:
            kind: text
            label: Mensaje

  assets:
    whitelist: ['stylesheets/screen.css', '^images/([^/]+)$']
